services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        POETRY_ENV: dev
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    container_name: fastapi-app
    image: fastapi-app:latest
    command: sh -c "umask 002 && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api/src:/app/src
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
