services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        POETRY_ENV: dev
    container_name: fastapi-app
    image: fastapi-app:latest
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api/src:/app/src
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
